title: Playgrounds
author:
  name: wotanut
  email: sam@sambot.dev

description: A place to showcase CSS challenges and frontendmentor solutions

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized-dark

  social_links:
    - { platform: github, user_url: "https://github.com/wotanut" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/sam-blewitt",
      }
